### PR TITLE
Forgot to update __init__.py to reflect new version

### PR DESCRIPTION
**Pull request by brandonusher**

### CODE REVIEW

**Comment by etianen** [comment]
I can never decide _when_ to update the version number. Now's a good a time as any. :)

**Comment by brandonusher** [comment]
How do updates get pushed to pip?

**Comment by etianen** [comment]
Manually, using `python sdist register upload` at the terminal. It corresponds with a manual git tagging of the same version number.

**Comment by brandonusher** [comment]
ah, thanks

**Comment by etianen** [comment]
I’ve always loved the idea of doing an automatic release when a git tag is added. 

http://docs.travis-ci.com/user/deployment/pypi/

However, the tricky thing seems to be automatically incrementing the version stored in the Python source code at the same.

**Pull request merged**
