### PR TITLE
Merge request for LDAP Over SSL/TLS Fix

### PR DESCRIPTION
**Pull request by dblanque**
Adds required use_ssl argument to ldap3.Server __init __function.

### CODE REVIEW

**Comment by etianen** [comment]
Thanks @dblanque for contributing this back! I was away on holiday, so have just got around to catching up on emails.

@githubuserx and @FlipperPA - I'm now completely confused about TLS handling by this library. What do you think about this PR?

**Comment by FlipperPA** [comment]
@etianen I think some of the issues here (as has happened in the past) may be different requirements for Active Directory and OpenLDAP. But I'm also a bit confused because the initial PR I made long ago worked for me with OpenLDAP.

I've been trying to access an Active Directory installation (not my wheelhouse), but work has recently done a re-org and I don't have the access to the MSFT side of the house I once did. Still trying!

**Comment by githubuserx** [comment]
In my experience many confuse the distinction between SSL and TLS. These terms are often used interchangably, but in the specific context of LDAP there is a big difference in how the connection is established.

"LDAP over SSL"
- usually connects over port 636
- uses URL prefix `ldaps://`
- establishes a secure channel immediatly on connection

"LDAP over TLS (StartTLS)" aka "LDAP Signing"
- usually connects over port 389
- uses URL prefix `ldap://`
- first establishes an insecure connection which is then upgraded to a secure channel by the mechanisms of StartTLS
  - uses an LDAP extended operation for StartTLS[^1] which the server software must support

@FlipperPA To my knowledge both MS AD and OpenLDAP support both connection variants although the configuration is certainly very different.

Now looking at the implementation of the `ldap3` package, it seems that the `use_ssl` parameter is only used to distinguish between which default port the connection should use, i.e. if `use_ssl=True`, port 636 is used, else port 389.
Additionally, the default port is also inferred from the URL prefix or if a port is explicitly specified.
Hence, if the specified LDAP URL starts with `ldaps://` and no port is given, it defaults to port 636, otherwise port 389.

This behaviour may not be perfectly clear from the ldap3 documentation, but can easily be verified by looking at the code[^2].
>host: name or ip or the complete url in the scheme://hostname:hostport format of the server (required) - port and scheme (ldap or ldaps) defined here have precedence over the parameters port and use_ssl

>use_ssl: specifies if the connection is on a secure port (defaults to False). When True the secure port is usually set to 636.

@dblanque Given my explanations above, I assume you are trying to connect to LDAPS on port 636, so it should work if you either add the `ldaps://` prefix or additionally specify the port 636. Even when `use_ssl` has the default value `False`.

[^1]: https://www.rfc-editor.org/rfc/rfc4511#section-4.14
[^2]: https://github.com/cannatag/ldap3/blob/dev/ldap3/core/server.py#L76

**Comment by etianen** [comment]
Thanks for the explanation and diving into the code!

I'm going to close this then, as it sounds like everything people need is already covered, and changing this parameter will only break existing installs.

**Comment by dblanque** [comment]
Damn I'm so sorry guys! I fumbled up TLS and SSL... could've broken everything :/

> @etianen I think some of the issues here (as has happened in the past) may be different requirements for Active Directory and OpenLDAP. But I'm also a bit confused because the initial PR I made long ago worked for me with OpenLDAP.
> 
> This change, however, appears to be for an older version (pre-TLS, SSL)?
> 
> @dblanque: Can you confirm whether you are using OpenLDAP or Active Directory, and which version?
> 
> I've been trying to access an Active Directory installation (not my wheelhouse), but work has recently done a re-org and I don't have the access to the MSFT side of the house I once did. Still trying!

I've tested a change similar to this (practically the same code, some differences elsewhere) with a Samba LDAP Server with LDAPS over SSL. Still haven't gotten to testing it with an Active Directory with SSL.

I have not tested it at all with OpenLDAP.

Does this mean that SSL is implemented and I have just not... seen it? Or is it something that has not been tested nor implemented yet. Just wondering if I can still help somehow.

**Comment by dblanque** [comment]
> @dblanque Given my explanations above, I assume you are trying to connect to LDAPS on port 636, so it should work if you either add the `ldaps://` prefix or additionally specify the port 636. Even when `use_ssl` has the default value `False`.

That is correct, I have tested it with a Samba LDAP Server on the default port _636_, however LDAPS **does not** work with the use_ssl value set to False (on the other hand, it does when set to True).

**Comment by githubuserx** [comment]
I just tested again with my setup and realized something I didn't before: If the port is set to 636 but the host URL (`LDAP_AUTH_URL`) starts with the `ldap://` prefix (w/o the `s`), it tries to connect without SSL even if `use_ssl=True`, which will likely not work on port 636. In other words, the `use_ssl` parameter only makes a difference if the URL prefix is omitted - and to connect over SSL without changing the default value of `use_ssl`, you *have to* specify the `ldaps://` prefix.

see https://github.com/cannatag/ldap3/blob/dev/ldap3/core/server.py#L88-L95

Other than that, it works as expected on my side, i.e. if I specify the correct URL prefix it connects over SSL.

**Comment by dblanque** [comment]
> I just tested again with my setup and realized something I didn't before: If the port is set to 636 but the host URL (`LDAP_AUTH_URL`) starts with the `ldap://` prefix (w/o the `s`), it tries to connect without SSL even if `use_ssl=True`, which will likely not work on port 636. In other words, the `use_ssl` parameter only makes a difference if the URL prefix is omitted - and to connect over SSL without changing the default value of `use_ssl`, you _have to_ specify the `ldaps://` prefix.
> 
> see https://github.com/cannatag/ldap3/blob/dev/ldap3/core/server.py#L88-L95
> 
> Other than that, it works as expected on my side, i.e. if I specify the correct URL prefix it connects over SSL.

I was just trying the same thing, even when forcing it to True it doesn't use it without the (s) in the ldap prefix. I don't even know how I managed to break it before, I honestly can't remember. Hopefully it was just a mis-configuration on my end or something.

Ah well, I'd rather be wrong and learn from this experience than accidentally detonate thousands of ldap connections 😂 

Thanks @githubuserx, thanks @etianen, thanks @FlipperPA!

_Regards_,
Dylan

**Comment by etianen** [comment]
Thanks for the follow-up! This stuff is hard!

**Pull request closed without merging**
