### PR TITLE
Support for setting prefixes that  support multiple backends

### PR DESCRIPTION
**Pull request by mmmduft**
- Add support for being loaded as multiple auth backends with configurable settings prefix to allow different configurations.
- Additional options for TLS and certificate validation
- Additional option 'ATTRIBUTES' to limit (or increase) the size of records returned by the server.

### CODE REVIEW

**Comment by mmmduft** [comment]
Add support for being loaded as multiple auth backends with configurable settings prefix to allow different configurations.
Additional options for TLS and certificate validation
Additional option 'ATTRIBUTES' to limit (or increase) the size of records returned by the server.

**Comment by etianen** [comment]
Sorry it took so long to get to this... I have a newborn and my time is very limited!

The extra settings look very welcome. Thanks for documenting them too!

What I'm not so sure about is the settings prefix concept. Django has a convention of a settings dict (see `DATABASES` and `CACHES`). It seems awkward to defy that convention.

**Comment by mmmduft** [comment]
Thank you. Makes sense I'll look to change to support a dictionary style configuration approach.

**Comment by etianen** [comment]
Can we do this as two PRs? One for the extra settings, and the other for
the dictionary config?

Let's start with the extra settings, since that is most straightforward

**Comment by mmmduft** [comment]
I'll re-submit the setting changes first.

**Pull request closed without merging**
