### PR TITLE
Add basic TLS support

### PR DESCRIPTION
**Pull request by saraheiting**
I was trying to use this package, but the LDAP server that I needed to connect to requires TLS. 

This pull request adds a setting to enable initiating TLS after connection.

### CODE REVIEW

**Comment by etianen** [comment]
Great! Thanks for contributing! :)

I can't push out a new release at the moment, as I'm on holiday in Scotland, but will get one sorted when I get back next Monday.

**Comment by etianen** [comment]
Hey, @saraheiting !

Just a heads-up, a security vulnerability was found in this feature where username and password could be transmitted in plain text before starting TLS. It's been patched in release 0.9.5, so you should probably upgrade your sites.

The fix is in a250194e2911e270a90b0eec2251343040a75ece, if you're interested. :)

**Comment by saraheiting** [comment]
Thanks so much for letting me know! Will update.

Sarah

**Comment by FlipperPA** [comment]
Wowzer, thanks for the update. Updating right now...

**Pull request merged**
