### PR TITLE
use serverpool to enable multiple auth servers

### PR DESCRIPTION
**Pull request by hho6643**
Make use of LDAP3's ServerPool to enable authentication against more than 1 LDAP server.

### CODE REVIEW

**Comment by etianen** [comment]
Sorry I haven't had a chance to review this! I'll have time next weekend.

**Review by etianen — COMMENTED** [review]
Sorry for the delay, this looks excellent.

There looks to be some linting errors. I've allowed workflows for you though. When you get the lints and tests passing, ping me, and I'll get this merged ASAP. :D

**Comment by hho6643** [comment]
Hi - I linted it on my machine, so that's better, but I either still don't have permission or (more likely) don't know how to run the lint tests here in github to verify the problem's fixed :(

**Comment by etianen** [comment]
Ugh. Damn bitcoin miners ruining GHA :(

I hit the actions button again. Let's see how it goes.

**Comment by etianen** [comment]
All pass! Merged! Will push a release sometime this week!

**Comment by etianen** [comment]
Thanks for your patience on this. :)

**Comment by hho6643** [comment]
Thanks a bunch!

**Comment by etianen** [comment]
Released as 0.14.0!

**Pull request merged**
