### PR TITLE
Fix: cannot import name 'six' from 'django.utils'

### PR DESCRIPTION
**Pull request by kevin-olbrich**
fixes https://github.com/django-auth-ldap/django-auth-ldap/issues/162

### CODE REVIEW

**Comment by kevin-olbrich** [comment]
tested & works

**Comment by kevin-olbrich** [comment]
Would you be so kind to test, merge and release a new version?
That would help me a lot!

**Comment by etianen** [comment]
Thanks for the MR!

The advice from Django is to simply drop Python 2 support at this point. I'm inclined to agree. That means dropping the `six` dependency and associated shims entirely.

**Comment by kevin-olbrich** [comment]
I‘m fine with that, as I never used Py2.

**Comment by etianen** [comment]
I've pushed a fix to master that adds Django 3.0 compatibility.

Unfortunately, my previous test LDAP server is now offline, so I had to switch test LDAP server. As part of this, I uncovered a problem where django-python3-ldap was a little slow cleaning up LDAP connections that failed to bind. This meant a small refactor of the LDAP connection logic.

I'd appreciate it if you could verify that the master branch works with your setup. If it does, I'll push out another release with Django 3.0 compatibility today.

**Comment by kevin-olbrich** [comment]
@etianen Seems to work. I did some quick tests (login, logout, etc.) and it works fine.

**Comment by kevin-olbrich** [comment]
@etianen I did not hear any complaints about the upgrade. I've moved one of my projects into prod (django 3.0 + django-python3-ldap master) and it works flawless.
If you release this version, my CD will pick it up and I can test all projects against that.

**Comment by etianen** [comment]
Released as v0.11.3. Thanks for auditing it!

**Comment by kevin-olbrich** [comment]
Thanks for maintaining this excellent piece of software! :-)

**Comment by kevin-olbrich** [comment]
Oops, I just realized my initial issue was filed against the wrong project (but fixed in the correct one :-) )

**Comment by etianen** [comment]
I did wonder about that! :P

**Pull request closed without merging**
