### PR TITLE
Use the last version of pyasn1 0.4.6

### PR DESCRIPTION
**Pull request by Briffou**
Is it possible to have a new release including the new version of pyasn1 ?

### CODE REVIEW

**Comment by etianen** [comment]
I've decided to widen the version specifiers in setup.py so that pyasn1 and ldap3 update automatically to the latest non-breaking change.

Historically, the combination of both libraries has introduced breaking changes quite regularly, but hopefully they're more stable now and it's safe to use version ranges once more.

https://github.com/etianen/django-python3-ldap/commit/0c0a714b63d66367b445a18484993fdfa8aae768

If the build passes, I'll push a new version.

**Comment by etianen** [comment]
Ah, unfortunately, the LDAP server I use to test against has gone away, so I can no longer run tests.

I'm reluctant to push out any releases until a new testing server can be found, and I'm unlikely to have time to do this in the near future.

I'm not sure what to do here, unfortunately.

**Comment by etianen** [comment]
That would be amazing. I didn't know we could do that.

**Comment by cannatag** [comment]
Hi all, the current 2.6 version of ldap3 doesn’t work with pyasn1 0.4.6. I will release a compatible version next week.
 If you want to test it you can get the dev branch from the cannatag/ldap3 repository here on github.

**Pull request closed without merging**
